### ISSUE TITLE
USB Audio doesn't work for videos with 5.1

### ISSUE THREAD

**Issue by d2dyno** [plexinc/plex-for-kodi#81] opened 2017-02-19 10:06 UTC
In the latest version of LibreELEC and Plex for Kodi, USB audio isn't working. I have the source selected within the Kodi settings (ALSA). Plex will play any videos that use 2.0 audio, but nothing with DTS/5.1 audio.

**Comment by ruuk** [comment] 2017-03-08 20:35
This sounds like Kodi/LibreELEC issue. I'm closing this issues as it does not seem be caused by the add-on. Feel free to re-open it if you have any information that points to the add-on itself as the cause.

**Closed by ruuk** 2017-03-08 20:35 UTC
