### ISSUE TITLE
Change big seek behaviour so that markers respect chapter markers inside files.

### ISSUE THREAD

**Issue by danjames92** [plexinc/plex-for-kodi#98] opened 2017-04-17 08:22 UTC
As most of us know, there are chapter markers inside of most movies / tv shows. Instead of dividing the file length by 12, I would love to see Big Seek to read a file and make the big seek markers line up so that they occur at the timestamp of the chapters.

If some of us have chapter thumbnail creation on, it would be wise to respect their timestamps also and show a preview thumbnail also.

Many thanks for your consideration of this feature.

**Comment by keithah** [comment] 2017-04-17 11:25
Duplicate of #9. Feel free to comment there, and not open up brand new GHI's for same functionality.

**Closed by keithah** 2017-04-17 11:25 UTC
