### ISSUE TITLE
"Sign In" does not work in Kodi Jarvis on Android 5.x

### ISSUE THREAD

**Issue by g1t-dlanor** [plexinc/plex-for-kodi#39] opened 2016-12-07 17:34 UTC
I have attempted to use the "Plex for Kodi" addon ("script.plex-0.0.93.zip") on some of my Android devices running Android 5.x OS versions. I have successfully installed the addon into various Kodi Jarvis versions, including the latest official stable release 16.1, but all attempts to use the addon fail in the same way.

When activating the "Sign In" command, either by touching its button on touchscreen, clicking the button with mouse, or pressing an 'Enter' key with that button selected, the result is always only that control focus exits from the addon returning to whatever menu was used to launch the 'Plex' addon. In some cases I've seen the screen where the sign-in code is to be generated flicker past, before exit to the previous menu, but only for a fraction of a second and no code was ever displayed. (Wouldn't matter even if it had been, as the addon exits in all cases anyway.)

As far as I can tell from my tests use of this addon under Android is impossible, at least for Android 5.x versions.

**Comment by ruuk** [comment] 2016-12-07 18:17
[script.plex-0.0.94a1.zip](https://github.com/plexinc/plex-for-kodi/files/637382/script.plex-0.0.94a1.zip)

Try this version. If it doesn't fix the issue, I will definitely need a log.

**Comment by jrmull** [comment] 2016-12-08 05:46
I'm seeing the same thing with 0.0.94a1 posted here on the Shield Android TV running the latest Kodi beta published through the Play Store (20161130-654f1b7). The pertinent part of the log:

00:34:22.157 T:1487915312  NOTICE: script.plex: Player: Idling...
00:34:22.157 T:1457764656  NOTICE: script.plex: Cron started
00:34:22.158 T:1457764656 WARNING: CSkinInfo: failed to load skin settings
0034:22.511 T:1457764656  NOTICE: script.plex: STARTED: 0.0.94a1
00:34:22.511 T:1457764656  NOTICE: script.plex: Initializing...
00:34:22.518 T:1457764656  NOTICE: script.plex: API: Starting selected server search, hoping for
00:34:22.520 T:1457764656  NOTICE: script.plex: Waiting for account initialization...
00:34:22.523 T:1457764656 WARNING: CSkinInfo: failed to load skin settings
00:34:24.061 T:1457764656 WARNING: Previous line repeats 2 times.
00:34:24.061 T:1457764656   ERROR: _________________________________________________________________________________
00:34:24.061 T:1457764656   ERROR: script.plex: ERROR:
00:34:24.061 T:1457764656   ERROR:     Traceback (most recent call last):
00:34:24.061 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/main.py", line 60, in _main
00:34:24.061 T:1457764656   ERROR:         if plex.init():
00:34:24.061 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/plex.py", line 240, in init
00:34:24.061 T:1457764656   ERROR:         token = authorize()
00:34:24.061 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/plex.py", line 299, in authorize
00:34:24.061 T:1457764656   ERROR:         pl = myplex.PinLogin()
00:34:24.061 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/_included_packages/plexnet/myplex.py", line 29, in __init__
00:34:24.062 T:1457764656   ERROR:         self._init()
00:34:24.062 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/_included_packages/plexnet/myplex.py", line 32, in _init
00:34:24.062 T:1457764656   ERROR:         response = http.POST(self.INIT)
00:34:24.062 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plex/lib/_included_packages/plexnet/http.py", line 23, in POST
00:34:24.062 T:1457764656   ERROR:         return requests.post(*args, headers=util.BASE_HEADERS.copy(), timeout=util.TIMEOUT, **kwargs)
00:34:24.062 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 107, in post
00:34:24.062 T:1457764656   ERROR:         return request('post', url, data=data, json=json, **kwargs)
00:34:24.062 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/api.py", line 53, in request
00:34:24.062 T:1457764656   ERROR:         return session.request(method=method, url=url, **kwargs)
00:34:24.062 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 468, in request
00:34:24.062 T:1457764656   ERROR:         resp = self.send(prep, **send_kwargs)
00:34:24.062 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 576, in send
00:34:24.062 T:1457764656   ERROR:         r = adapter.send(request, **kwargs)
00:34:24.062 T:1457764656   ERROR:       File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 437, in send
00:34:24.062 T:1457764656   ERROR:         raise ConnectionError(e, request=request)
00:34:24.062 T:1457764656   ERROR:     ConnectionError: HTTPSConnectionPool(host='my.plexapp.com', port=443): Max retries exceeded with url: /pins.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x5f367dd0>: Failed to establish a new connection: [Errno 22] Invalid argument',))
00:34:24.062 T:1457764656   ERROR: _________________________________________________________________________________
00:34:24.062 T:1457764656   ERROR: `
00:34:24.062 T:1457764656  NOTICE: script.plex: SHUTTING DOWN...
00:34:24.063 T:1457764656  NOTICE: script.plex: Checking for any remaining threads
00:34:24.063 T:1457764656  NOTICE: script.plex: Waiting on: PLAYER:MONITOR...
00:34:24.091 T:1488959792  NOTICE: script.plex: Cron stopped
00:34:24.091 T:1487915312  NOTICE: script.plex: Player: Closed
00:34:24.091 T:1457764656  NOTICE: script.plex: FINISHED

**Comment by Kovrinic** [comment] 2016-12-08 06:33
Tried `0.0.94a1`, but still same results as [before](http://forums.plex.tv/discussion/comment/1317187/#Comment_1317187).

Log: https://paste.ubuntu.com/23597112/

**Comment by keithah** [comment] 2016-12-08 06:35
@jrmull please next time use a pastern like paste.ubuntu.com, and paste in the full log, so we know version/etc.

Looks like its a bug on our side, thanks for reporting! We'll track down the issue and get a new build out tomorrow ASAP.

**Comment by ruuk** [comment] 2016-12-08 12:22
@Kovrinic: In your case, the error is ```Non-recoverable failure in name resolution```. 
Is it possible there's something going on with that device?

**Comment by ruuk** [comment] 2016-12-08 18:39
@jrmull:
[script.plex-0.0.94a2.zip](https://github.com/plexinc/plex-for-kodi/files/640280/script.plex-0.0.94a2.zip)

Can you run this version and get me the log from it. I'm not sure yet what the error in your log means, so I'm making some guesses and I've added some extra logging so hopefully I can see what's going on. Thanks.

**Comment by jrmull** [comment] 2016-12-09 05:10
@ruuk  As requested: [https://paste.ubuntu.com/23601910/](https://paste.ubuntu.com/23601910/)

**Comment by Kovrinic** [comment] 2016-12-09 05:46
`0.0.94a2` log file https://paste.ubuntu.com/23602066/

**Comment by ruuk** [comment] 2016-12-09 06:05
@jrmull: Thanks for the log. It gave me the info I needed, but unfortunately, it didn't help me solve the issue. I'll keep investigating.

@Kovrinic: You're error is unrelated to jrmull's error. It seems to be a problem with name resolution (i.e. getting the IP address that's associated with my.plexapp.com) which is something handled by the OS.
From the log it looks like you're running this on a phone? Is this via wi-fi or data? Also note that the add-on does not really support touch devices (like Kodi it is primarily designed with a TV interface). It might work, but the experience won't be great.

@g1t-dlanor: Did you have any luck? If not I still need a log from you, as fairly likely that your issue is not the same as either of these.

**Comment by Kovrinic** [comment] 2016-12-09 06:15
> From the log it looks like you're running this on a phone? Is this via wi-fi or data?

Yes, I was testing from a phone over WiFi only.

> Also note that the add-on does not really support touch devices (like Kodi it is primarily designed with a TV interface). It might work, but the experience won't be great.

Okay.  To be honest, I'm not a Kodi user, was just testing _Plex for Kodi_ for the sake of testing and noticed the similar error.

**Comment by Kovrinic** [comment] 2016-12-10 00:12
Sorry, error was on my end.  Plex for Kodi `0.0.93` working.  My pi-hole was blocking `my.plexapp.com` for some reason.

**Comment by keithah** [comment] 2016-12-10 05:21
Thanks for letting us know @Kovrinic.

As @ruuk said, @g1t-dlanor, please post a log. 

@jrmull Can you try to install Kodi + add-on on a PC/mac on the same network and see if it works? Trying to isolate the issue.

**Comment by keithah** [comment] 2016-12-14 07:18
@jrmull Can you try again and let me know if 0.0.95 works any better? Plex also changed some stuff on their end as well.

**Comment by g1t-dlanor** [comment] 2016-12-14 08:40
@ruuk @keithah 
I've just posted a ZIP with logs in the Plex forums, but I'll repeat it here too since this is the official issue site.
These logs were taken after making a fresh install of 'Kodi 16.1 Jarvis (Stable)' on my 'Nexus7 (2012)'.
All I've done with this Kodi is basic configuration and installing my favourite vertical menu skin (Amber) before installing and testing 'script.plex-0.0.95.zip', with identical failure as on all my other android devices. (Popup saying that connection failed to my.plexapp.com.)
Just to avoid misunderstandings here I should add that I've had identical failures also when using the default 'Confluence' skin, so I don't think the skin has any influence here. (Though dependency addons of skins you use may be what hides the problem at your end, if my conclusion below is correct.)

I performed the test in two consecutive sessions, and have included both "kodi.log" and "kodi.old.log" so you can see that the error is consistent between sessions.
Having glanced through the logs my main impression is that you have some undeclared dependency that does not affect your own installations because there you already have some additional addon or configuration that all my setups lack.

Best regards: g1t-dlanor

Edit: I should add that "kodi.old.log" includes some networking error messages that are unrelated to the issue, as they resulted from my adding LAN network locations as sources for the Kodi file manager, which apparently starts each such access attempt in anonymous mode which my servers naturally refuse, with Kodi allowing me to define login data for those sources only after generating an error for each one. So ignore the error messages related to smb://RA1 and similar LAN addresses. (They all work fine after Kodi allowed me to add the passwords.)
[Kodi for Plex logs from Nexus7.zip](https://github.com/plexinc/plex-for-kodi/files/651140/Kodi.for.Plex.logs.from.Nexus7.zip)

**Comment by ruuk** [comment] 2016-12-14 12:33
@g1t-dlanor: Thanks for the logs. Just looked at them and there are actually no script errors in the log. I did notice that when added the dialog I forgot to log the contents of the error when capturing it, so I'll add that back in the next version. What I do know is that it is failing to connect to my.plexapp.com. We'll have to wait for 0.0.96 to get the contents of the error and see the exact reason. But similar errors from other users logs so far indicate it's not an issue with the add-on directly. But let's get a new log on the next version (sorry) and we'll see if we find out something new.

**Comment by g1t-dlanor** [comment] 2016-12-14 15:36
@keithah 
I have now discovered what it is that triggered the authentication failures on my Android devices.
It is not any bug or problem with the software, though it still is a worrisome issue, as explained below.

All the devices I tested with so far have ad-blocking active, using a 'hosts' file blocking known advertising sites.
When I deactivated this ad-blocking, restoring an empty 'hosts' file and rebooting, 'Plex for Kodi' authenticated.
I then made a search in the ad-blocking hosts file and found an entry for "my.plexapp.com".
Now the big question is WHY the 'Plex for Kodi' authentication site is included by ad-block list maintainers...???

I can fix this on my own devices simply by adding "my.plexapp.com" to a local whitelist of the "AdAway" app.
This will make it ignore the existence of that URL in future updates of the 'hosts' file from the maintained lists.
Still, I find it a bit odd that this is necessary, since it wasn't necessary to run the normal 'Plex for Android' client, which presumably uses a similar authentication. But apparently it doesn't use exactly the same URL...

As I see it two things should be done about this issue. One is to investigate WHY ad-blockers include this site in their lists, and if possible convince them to stop doing so. The other is to add a warning to the 'Plex for Kodi' release pages, informing users that ad-blocking may currently interfere with the authentication of this Plex client, unless they add a whitelist exception for "my.plexapp.com".

Best regards: dlanor

Edit: I just noted the planned change to use "plex.tv" instead of "my.plexapp.com", which will fix this issue.

**Comment by ruuk** [comment] 2016-12-14 18:58
The issue of the OP (g1t-dlanor) should be fixed buy the change made for issue #50.

@jrmull: When 0.0.96 is available, please let us know if it fixes your issue.

Thanks all for the help and logs.

**Comment by jrmull** [comment] 2016-12-14 20:28
@ruuk are the new builds only posted on the forum?

**Comment by ruuk** [comment] 2016-12-14 20:29
Now in the official Kodi repo, but you can use this:
[script.plex-0.0.96.zip](https://github.com/plexinc/plex-for-kodi/files/652795/script.plex-0.0.96.zip)

**Comment by keithah** [comment] 2016-12-15 02:05
I'm keeping this open until @jrmull is able to test, but hopefully should be resolved.

**Comment by jrmull** [comment] 2016-12-15 15:34
@keithah The new version is working for me now - I think it was the switch to using plex.tv that did the trick.  Thanks.

**Comment by keithah** [comment] 2016-12-16 00:43
Great, glad to hear @jrmull!

**Closed by keithah** 2016-12-16 00:43 UTC
