### ISSUE TITLE
Plex for Kodi on Xbox obe

### ISSUE THREAD

**Issue by khyaniv30** [plexinc/plex-for-kodi#161] opened 2018-02-14 19:49 UTC
Xbox one runs only one version - Kodi 18 alpha.
After installing the add-on and activate my account, it shows screen with 3 dots and it stuck there. 
Can you please fix it ?

**Comment by ruuk** [comment] 2018-02-15 02:35
Closing as a duplicate of #146

**Closed** 2018-02-15 02:35 UTC
